# Generated by Django 5.2.3 on 2025-06-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='route',
        ),
    ]
