# Generated by Django 5.2.3 on 2025-06-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_created_at_alter_booking_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
